### ISSUE TITLE
USER STORY: Add a video to home page

### ISSUE THREAD

**Issue by claudio-cruz** [claudio-cruz/love-running#3]
As a **user** I can **see a motivational running video** so that **I get motivated for the future run events.**

## Tasks
  - [ ] Major design changes.
  - [ ] Pick a Motivational video.
  - [ ] Insert the motivational video to the home page.
